# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='id_cart',
        ),
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
