# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.barcode


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171022_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, unique=True, verbose_name='Nome')),
                ('preco', models.IntegerField(max_length=8, verbose_name='Preco')),
                ('barcode', models.IntegerField(unique=True, validators=[helpers.barcode.GTIN], verbose_name='Barcode')),
            ],
        ),
    ]
