# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=6, max_length=8, verbose_name='Peso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='products_name',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Produto'),
            preserve_default=False,
        ),
    ]
