# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171118_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Cart', verbose_name='Carrinho'),
        ),
    ]
