# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171118_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='id_user',
            new_name='id_cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
