# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=8, verbose_name='Preco')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagem',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='preco',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='id_product',
        ),
        migrations.AddField(
            model_name='purchase_product',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
        migrations.AddField(
            model_name='purchase_product',
            name='id_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Purchase'),
        ),
    ]
