# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171118_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=50, max_length=8, verbose_name='Peso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_link',
            field=models.URLField(default='-', verbose_name='Link de Pagamento'),
        ),
    ]
