# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171118_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='hashed_id',
            field=models.CharField(default=123, max_length=13, verbose_name='Hash'),
            preserve_default=False,
        ),
    ]
