# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171024_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cachorro',
        ),
        migrations.RemoveField(
            model_name='purchase_product',
            name='id_product',
        ),
        migrations.RemoveField(
            model_name='purchase_product',
            name='id_purchase',
        ),
        migrations.AddField(
            model_name='purchase',
            name='products',
            field=models.ManyToManyField(to='core.Product'),
        ),
        migrations.DeleteModel(
            name='Purchase_Product',
        ),
    ]
