# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171130_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='weigth_validation',
            field=models.BooleanField(default=False),
        ),
    ]
